#include <stdio.h>

int tests = 0;
int failures = 0;
#define check(actual, expected) \
    tests++; if(((actual)) != ((expected))) { printf("test failed: line %d\n", __LINE__); failures++; }

void u8_rsh_u8() {
    unsigned char i;
    unsigned char j;
    i = 0;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 128;  j = 1;
    check((i >> j), 64);
    check((i >> j) < 0, 0);
    i = 128;  j = 2;
    check((i >> j), 32);
    check((i >> j) < 0, 0);
    i = 128;  j = 3;
    check((i >> j), 16);
    check((i >> j) < 0, 0);
    i = 128;  j = 4;
    check((i >> j), 8);
    check((i >> j) < 0, 0);
    i = 128;  j = 5;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 128;  j = 6;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 192;  j = 1;
    check((i >> j), 96);
    check((i >> j) < 0, 0);
    i = 192;  j = 2;
    check((i >> j), 48);
    check((i >> j) < 0, 0);
    i = 192;  j = 3;
    check((i >> j), 24);
    check((i >> j) < 0, 0);
    i = 192;  j = 4;
    check((i >> j), 12);
    check((i >> j) < 0, 0);
    i = 192;  j = 5;
    check((i >> j), 6);
    check((i >> j) < 0, 0);
    i = 192;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 255;  j = 1;
    check((i >> j), 127);
    check((i >> j) < 0, 0);
    i = 255;  j = 2;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 255;  j = 3;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 255;  j = 4;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 255;  j = 5;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 255;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
}
void u8_rsh_i8() {
    unsigned char i;
    signed char j;
    i = 0;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 128;  j = 1;
    check((i >> j), 64);
    check((i >> j) < 0, 0);
    i = 128;  j = 2;
    check((i >> j), 32);
    check((i >> j) < 0, 0);
    i = 128;  j = 3;
    check((i >> j), 16);
    check((i >> j) < 0, 0);
    i = 128;  j = 4;
    check((i >> j), 8);
    check((i >> j) < 0, 0);
    i = 128;  j = 5;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 128;  j = 6;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 192;  j = 1;
    check((i >> j), 96);
    check((i >> j) < 0, 0);
    i = 192;  j = 2;
    check((i >> j), 48);
    check((i >> j) < 0, 0);
    i = 192;  j = 3;
    check((i >> j), 24);
    check((i >> j) < 0, 0);
    i = 192;  j = 4;
    check((i >> j), 12);
    check((i >> j) < 0, 0);
    i = 192;  j = 5;
    check((i >> j), 6);
    check((i >> j) < 0, 0);
    i = 192;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 255;  j = 1;
    check((i >> j), 127);
    check((i >> j) < 0, 0);
    i = 255;  j = 2;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 255;  j = 3;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 255;  j = 4;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 255;  j = 5;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 255;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
}
void u8_rsh_u16() {
    unsigned char i;
    unsigned int j;
    i = 0;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 128;  j = 1;
    check((i >> j), 64);
    check((i >> j) < 0, 0);
    i = 128;  j = 2;
    check((i >> j), 32);
    check((i >> j) < 0, 0);
    i = 128;  j = 3;
    check((i >> j), 16);
    check((i >> j) < 0, 0);
    i = 128;  j = 4;
    check((i >> j), 8);
    check((i >> j) < 0, 0);
    i = 128;  j = 5;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 128;  j = 6;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 192;  j = 1;
    check((i >> j), 96);
    check((i >> j) < 0, 0);
    i = 192;  j = 2;
    check((i >> j), 48);
    check((i >> j) < 0, 0);
    i = 192;  j = 3;
    check((i >> j), 24);
    check((i >> j) < 0, 0);
    i = 192;  j = 4;
    check((i >> j), 12);
    check((i >> j) < 0, 0);
    i = 192;  j = 5;
    check((i >> j), 6);
    check((i >> j) < 0, 0);
    i = 192;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 255;  j = 1;
    check((i >> j), 127);
    check((i >> j) < 0, 0);
    i = 255;  j = 2;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 255;  j = 3;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 255;  j = 4;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 255;  j = 5;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 255;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
}
void u8_rsh_i16() {
    unsigned char i;
    int j;
    i = 0;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 128;  j = 1;
    check((i >> j), 64);
    check((i >> j) < 0, 0);
    i = 128;  j = 2;
    check((i >> j), 32);
    check((i >> j) < 0, 0);
    i = 128;  j = 3;
    check((i >> j), 16);
    check((i >> j) < 0, 0);
    i = 128;  j = 4;
    check((i >> j), 8);
    check((i >> j) < 0, 0);
    i = 128;  j = 5;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 128;  j = 6;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 192;  j = 1;
    check((i >> j), 96);
    check((i >> j) < 0, 0);
    i = 192;  j = 2;
    check((i >> j), 48);
    check((i >> j) < 0, 0);
    i = 192;  j = 3;
    check((i >> j), 24);
    check((i >> j) < 0, 0);
    i = 192;  j = 4;
    check((i >> j), 12);
    check((i >> j) < 0, 0);
    i = 192;  j = 5;
    check((i >> j), 6);
    check((i >> j) < 0, 0);
    i = 192;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 255;  j = 1;
    check((i >> j), 127);
    check((i >> j) < 0, 0);
    i = 255;  j = 2;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 255;  j = 3;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 255;  j = 4;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 255;  j = 5;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 255;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
}
void u8_rsh_i32() {
    unsigned char i;
    long j;
    i = 0;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 0;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 128;  j = 1;
    check((i >> j), 64);
    check((i >> j) < 0, 0);
    i = 128;  j = 2;
    check((i >> j), 32);
    check((i >> j) < 0, 0);
    i = 128;  j = 3;
    check((i >> j), 16);
    check((i >> j) < 0, 0);
    i = 128;  j = 4;
    check((i >> j), 8);
    check((i >> j) < 0, 0);
    i = 128;  j = 5;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 128;  j = 6;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 192;  j = 1;
    check((i >> j), 96);
    check((i >> j) < 0, 0);
    i = 192;  j = 2;
    check((i >> j), 48);
    check((i >> j) < 0, 0);
    i = 192;  j = 3;
    check((i >> j), 24);
    check((i >> j) < 0, 0);
    i = 192;  j = 4;
    check((i >> j), 12);
    check((i >> j) < 0, 0);
    i = 192;  j = 5;
    check((i >> j), 6);
    check((i >> j) < 0, 0);
    i = 192;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 255;  j = 1;
    check((i >> j), 127);
    check((i >> j) < 0, 0);
    i = 255;  j = 2;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 255;  j = 3;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 255;  j = 4;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 255;  j = 5;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 255;  j = 6;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
}
int main() {
    u8_rsh_u8();
    u8_rsh_i8();
    u8_rsh_u16();
    u8_rsh_i16();
    u8_rsh_i32();
    printf("%s: %d tests finished, %d failures.\n",
    __FILE__, tests, failures);
}

