#include <stdio.h>

int tests = 0;
int failures = 0;
#define check(actual, expected) \
    tests++; if(((actual)) != ((expected))) { printf("test failed: line %d\n", __LINE__); failures++; }

void i16_lsh_u8() {
    int i;
    unsigned char j;
    i = -32768;  j = 1;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 2;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 3;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 4;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 5;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 6;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -113;  j = 1;
    check((i << j), -226);
    check((i << j) < 0, 1);
    i = -113;  j = 2;
    check((i << j), -452);
    check((i << j) < 0, 1);
    i = -113;  j = 3;
    check((i << j), -904);
    check((i << j) < 0, 1);
    i = -113;  j = 4;
    check((i << j), -1808);
    check((i << j) < 0, 1);
    i = -113;  j = 5;
    check((i << j), -3616);
    check((i << j) < 0, 1);
    i = -113;  j = 6;
    check((i << j), -7232);
    check((i << j) < 0, 1);
    i = -1;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = -1;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = -1;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = -1;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = -1;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = -1;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
    i = 1;  j = 1;
    check((i << j), 2);
    check((i << j) < 0, 0);
    i = 1;  j = 2;
    check((i << j), 4);
    check((i << j) < 0, 0);
    i = 1;  j = 3;
    check((i << j), 8);
    check((i << j) < 0, 0);
    i = 1;  j = 4;
    check((i << j), 16);
    check((i << j) < 0, 0);
    i = 1;  j = 5;
    check((i << j), 32);
    check((i << j) < 0, 0);
    i = 1;  j = 6;
    check((i << j), 64);
    check((i << j) < 0, 0);
    i = 36;  j = 1;
    check((i << j), 72);
    check((i << j) < 0, 0);
    i = 36;  j = 2;
    check((i << j), 144);
    check((i << j) < 0, 0);
    i = 36;  j = 3;
    check((i << j), 288);
    check((i << j) < 0, 0);
    i = 36;  j = 4;
    check((i << j), 576);
    check((i << j) < 0, 0);
    i = 36;  j = 5;
    check((i << j), 1152);
    check((i << j) < 0, 0);
    i = 36;  j = 6;
    check((i << j), 2304);
    check((i << j) < 0, 0);
    i = 32767;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = 32767;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = 32767;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = 32767;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = 32767;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = 32767;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
}
void i16_lsh_i8() {
    int i;
    signed char j;
    i = -32768;  j = 1;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 2;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 3;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 4;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 5;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 6;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -113;  j = 1;
    check((i << j), -226);
    check((i << j) < 0, 1);
    i = -113;  j = 2;
    check((i << j), -452);
    check((i << j) < 0, 1);
    i = -113;  j = 3;
    check((i << j), -904);
    check((i << j) < 0, 1);
    i = -113;  j = 4;
    check((i << j), -1808);
    check((i << j) < 0, 1);
    i = -113;  j = 5;
    check((i << j), -3616);
    check((i << j) < 0, 1);
    i = -113;  j = 6;
    check((i << j), -7232);
    check((i << j) < 0, 1);
    i = -1;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = -1;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = -1;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = -1;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = -1;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = -1;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
    i = 1;  j = 1;
    check((i << j), 2);
    check((i << j) < 0, 0);
    i = 1;  j = 2;
    check((i << j), 4);
    check((i << j) < 0, 0);
    i = 1;  j = 3;
    check((i << j), 8);
    check((i << j) < 0, 0);
    i = 1;  j = 4;
    check((i << j), 16);
    check((i << j) < 0, 0);
    i = 1;  j = 5;
    check((i << j), 32);
    check((i << j) < 0, 0);
    i = 1;  j = 6;
    check((i << j), 64);
    check((i << j) < 0, 0);
    i = 36;  j = 1;
    check((i << j), 72);
    check((i << j) < 0, 0);
    i = 36;  j = 2;
    check((i << j), 144);
    check((i << j) < 0, 0);
    i = 36;  j = 3;
    check((i << j), 288);
    check((i << j) < 0, 0);
    i = 36;  j = 4;
    check((i << j), 576);
    check((i << j) < 0, 0);
    i = 36;  j = 5;
    check((i << j), 1152);
    check((i << j) < 0, 0);
    i = 36;  j = 6;
    check((i << j), 2304);
    check((i << j) < 0, 0);
    i = 32767;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = 32767;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = 32767;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = 32767;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = 32767;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = 32767;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
}
void i16_lsh_u16() {
    int i;
    unsigned int j;
    i = -32768;  j = 1;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 2;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 3;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 4;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 5;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 6;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -113;  j = 1;
    check((i << j), -226);
    check((i << j) < 0, 1);
    i = -113;  j = 2;
    check((i << j), -452);
    check((i << j) < 0, 1);
    i = -113;  j = 3;
    check((i << j), -904);
    check((i << j) < 0, 1);
    i = -113;  j = 4;
    check((i << j), -1808);
    check((i << j) < 0, 1);
    i = -113;  j = 5;
    check((i << j), -3616);
    check((i << j) < 0, 1);
    i = -113;  j = 6;
    check((i << j), -7232);
    check((i << j) < 0, 1);
    i = -1;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = -1;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = -1;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = -1;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = -1;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = -1;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
    i = 1;  j = 1;
    check((i << j), 2);
    check((i << j) < 0, 0);
    i = 1;  j = 2;
    check((i << j), 4);
    check((i << j) < 0, 0);
    i = 1;  j = 3;
    check((i << j), 8);
    check((i << j) < 0, 0);
    i = 1;  j = 4;
    check((i << j), 16);
    check((i << j) < 0, 0);
    i = 1;  j = 5;
    check((i << j), 32);
    check((i << j) < 0, 0);
    i = 1;  j = 6;
    check((i << j), 64);
    check((i << j) < 0, 0);
    i = 36;  j = 1;
    check((i << j), 72);
    check((i << j) < 0, 0);
    i = 36;  j = 2;
    check((i << j), 144);
    check((i << j) < 0, 0);
    i = 36;  j = 3;
    check((i << j), 288);
    check((i << j) < 0, 0);
    i = 36;  j = 4;
    check((i << j), 576);
    check((i << j) < 0, 0);
    i = 36;  j = 5;
    check((i << j), 1152);
    check((i << j) < 0, 0);
    i = 36;  j = 6;
    check((i << j), 2304);
    check((i << j) < 0, 0);
    i = 32767;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = 32767;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = 32767;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = 32767;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = 32767;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = 32767;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
}
void i16_lsh_i16() {
    int i;
    int j;
    i = -32768;  j = 1;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 2;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 3;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 4;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 5;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 6;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -113;  j = 1;
    check((i << j), -226);
    check((i << j) < 0, 1);
    i = -113;  j = 2;
    check((i << j), -452);
    check((i << j) < 0, 1);
    i = -113;  j = 3;
    check((i << j), -904);
    check((i << j) < 0, 1);
    i = -113;  j = 4;
    check((i << j), -1808);
    check((i << j) < 0, 1);
    i = -113;  j = 5;
    check((i << j), -3616);
    check((i << j) < 0, 1);
    i = -113;  j = 6;
    check((i << j), -7232);
    check((i << j) < 0, 1);
    i = -1;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = -1;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = -1;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = -1;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = -1;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = -1;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
    i = 1;  j = 1;
    check((i << j), 2);
    check((i << j) < 0, 0);
    i = 1;  j = 2;
    check((i << j), 4);
    check((i << j) < 0, 0);
    i = 1;  j = 3;
    check((i << j), 8);
    check((i << j) < 0, 0);
    i = 1;  j = 4;
    check((i << j), 16);
    check((i << j) < 0, 0);
    i = 1;  j = 5;
    check((i << j), 32);
    check((i << j) < 0, 0);
    i = 1;  j = 6;
    check((i << j), 64);
    check((i << j) < 0, 0);
    i = 36;  j = 1;
    check((i << j), 72);
    check((i << j) < 0, 0);
    i = 36;  j = 2;
    check((i << j), 144);
    check((i << j) < 0, 0);
    i = 36;  j = 3;
    check((i << j), 288);
    check((i << j) < 0, 0);
    i = 36;  j = 4;
    check((i << j), 576);
    check((i << j) < 0, 0);
    i = 36;  j = 5;
    check((i << j), 1152);
    check((i << j) < 0, 0);
    i = 36;  j = 6;
    check((i << j), 2304);
    check((i << j) < 0, 0);
    i = 32767;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = 32767;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = 32767;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = 32767;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = 32767;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = 32767;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
}
void i16_lsh_i32() {
    int i;
    long j;
    i = -32768;  j = 1;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 2;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 3;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 4;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 5;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -32768;  j = 6;
    check((i << j), 0);
    check((i << j) < 0, 0);
    i = -113;  j = 1;
    check((i << j), -226);
    check((i << j) < 0, 1);
    i = -113;  j = 2;
    check((i << j), -452);
    check((i << j) < 0, 1);
    i = -113;  j = 3;
    check((i << j), -904);
    check((i << j) < 0, 1);
    i = -113;  j = 4;
    check((i << j), -1808);
    check((i << j) < 0, 1);
    i = -113;  j = 5;
    check((i << j), -3616);
    check((i << j) < 0, 1);
    i = -113;  j = 6;
    check((i << j), -7232);
    check((i << j) < 0, 1);
    i = -1;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = -1;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = -1;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = -1;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = -1;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = -1;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
    i = 1;  j = 1;
    check((i << j), 2);
    check((i << j) < 0, 0);
    i = 1;  j = 2;
    check((i << j), 4);
    check((i << j) < 0, 0);
    i = 1;  j = 3;
    check((i << j), 8);
    check((i << j) < 0, 0);
    i = 1;  j = 4;
    check((i << j), 16);
    check((i << j) < 0, 0);
    i = 1;  j = 5;
    check((i << j), 32);
    check((i << j) < 0, 0);
    i = 1;  j = 6;
    check((i << j), 64);
    check((i << j) < 0, 0);
    i = 36;  j = 1;
    check((i << j), 72);
    check((i << j) < 0, 0);
    i = 36;  j = 2;
    check((i << j), 144);
    check((i << j) < 0, 0);
    i = 36;  j = 3;
    check((i << j), 288);
    check((i << j) < 0, 0);
    i = 36;  j = 4;
    check((i << j), 576);
    check((i << j) < 0, 0);
    i = 36;  j = 5;
    check((i << j), 1152);
    check((i << j) < 0, 0);
    i = 36;  j = 6;
    check((i << j), 2304);
    check((i << j) < 0, 0);
    i = 32767;  j = 1;
    check((i << j), -2);
    check((i << j) < 0, 1);
    i = 32767;  j = 2;
    check((i << j), -4);
    check((i << j) < 0, 1);
    i = 32767;  j = 3;
    check((i << j), -8);
    check((i << j) < 0, 1);
    i = 32767;  j = 4;
    check((i << j), -16);
    check((i << j) < 0, 1);
    i = 32767;  j = 5;
    check((i << j), -32);
    check((i << j) < 0, 1);
    i = 32767;  j = 6;
    check((i << j), -64);
    check((i << j) < 0, 1);
}
int main() {
    i16_lsh_u8();
    i16_lsh_i8();
    i16_lsh_u16();
    i16_lsh_i16();
    i16_lsh_i32();
    printf("%s: %d tests finished, %d failures.\n",
    __FILE__, tests, failures);
}

