#include <stdio.h>

int tests = 0;
int failures = 0;
#define check(actual, expected) \
    tests++; if(((actual)) != ((expected))) { printf("test failed: line %d\n", __LINE__); failures++; }

void i16_rsh_u8() {
    int i;
    unsigned char j;
    i = -32768;  j = 1;
    check((i >> j), -16384);
    check((i >> j) < 0, 1);
    i = -32768;  j = 2;
    check((i >> j), -8192);
    check((i >> j) < 0, 1);
    i = -32768;  j = 3;
    check((i >> j), -4096);
    check((i >> j) < 0, 1);
    i = -32768;  j = 4;
    check((i >> j), -2048);
    check((i >> j) < 0, 1);
    i = -32768;  j = 5;
    check((i >> j), -1024);
    check((i >> j) < 0, 1);
    i = -32768;  j = 6;
    check((i >> j), -512);
    check((i >> j) < 0, 1);
    i = -113;  j = 1;
    check((i >> j), -57);
    check((i >> j) < 0, 1);
    i = -113;  j = 2;
    check((i >> j), -29);
    check((i >> j) < 0, 1);
    i = -113;  j = 3;
    check((i >> j), -15);
    check((i >> j) < 0, 1);
    i = -113;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -113;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -113;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 32767;  j = 1;
    check((i >> j), 16383);
    check((i >> j) < 0, 0);
    i = 32767;  j = 2;
    check((i >> j), 8191);
    check((i >> j) < 0, 0);
    i = 32767;  j = 3;
    check((i >> j), 4095);
    check((i >> j) < 0, 0);
    i = 32767;  j = 4;
    check((i >> j), 2047);
    check((i >> j) < 0, 0);
    i = 32767;  j = 5;
    check((i >> j), 1023);
    check((i >> j) < 0, 0);
    i = 32767;  j = 6;
    check((i >> j), 511);
    check((i >> j) < 0, 0);
}
void i16_rsh_i8() {
    int i;
    signed char j;
    i = -32768;  j = 1;
    check((i >> j), -16384);
    check((i >> j) < 0, 1);
    i = -32768;  j = 2;
    check((i >> j), -8192);
    check((i >> j) < 0, 1);
    i = -32768;  j = 3;
    check((i >> j), -4096);
    check((i >> j) < 0, 1);
    i = -32768;  j = 4;
    check((i >> j), -2048);
    check((i >> j) < 0, 1);
    i = -32768;  j = 5;
    check((i >> j), -1024);
    check((i >> j) < 0, 1);
    i = -32768;  j = 6;
    check((i >> j), -512);
    check((i >> j) < 0, 1);
    i = -113;  j = 1;
    check((i >> j), -57);
    check((i >> j) < 0, 1);
    i = -113;  j = 2;
    check((i >> j), -29);
    check((i >> j) < 0, 1);
    i = -113;  j = 3;
    check((i >> j), -15);
    check((i >> j) < 0, 1);
    i = -113;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -113;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -113;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 32767;  j = 1;
    check((i >> j), 16383);
    check((i >> j) < 0, 0);
    i = 32767;  j = 2;
    check((i >> j), 8191);
    check((i >> j) < 0, 0);
    i = 32767;  j = 3;
    check((i >> j), 4095);
    check((i >> j) < 0, 0);
    i = 32767;  j = 4;
    check((i >> j), 2047);
    check((i >> j) < 0, 0);
    i = 32767;  j = 5;
    check((i >> j), 1023);
    check((i >> j) < 0, 0);
    i = 32767;  j = 6;
    check((i >> j), 511);
    check((i >> j) < 0, 0);
}
void i16_rsh_u16() {
    int i;
    unsigned int j;
    i = -32768;  j = 1;
    check((i >> j), -16384);
    check((i >> j) < 0, 1);
    i = -32768;  j = 2;
    check((i >> j), -8192);
    check((i >> j) < 0, 1);
    i = -32768;  j = 3;
    check((i >> j), -4096);
    check((i >> j) < 0, 1);
    i = -32768;  j = 4;
    check((i >> j), -2048);
    check((i >> j) < 0, 1);
    i = -32768;  j = 5;
    check((i >> j), -1024);
    check((i >> j) < 0, 1);
    i = -32768;  j = 6;
    check((i >> j), -512);
    check((i >> j) < 0, 1);
    i = -113;  j = 1;
    check((i >> j), -57);
    check((i >> j) < 0, 1);
    i = -113;  j = 2;
    check((i >> j), -29);
    check((i >> j) < 0, 1);
    i = -113;  j = 3;
    check((i >> j), -15);
    check((i >> j) < 0, 1);
    i = -113;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -113;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -113;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 32767;  j = 1;
    check((i >> j), 16383);
    check((i >> j) < 0, 0);
    i = 32767;  j = 2;
    check((i >> j), 8191);
    check((i >> j) < 0, 0);
    i = 32767;  j = 3;
    check((i >> j), 4095);
    check((i >> j) < 0, 0);
    i = 32767;  j = 4;
    check((i >> j), 2047);
    check((i >> j) < 0, 0);
    i = 32767;  j = 5;
    check((i >> j), 1023);
    check((i >> j) < 0, 0);
    i = 32767;  j = 6;
    check((i >> j), 511);
    check((i >> j) < 0, 0);
}
void i16_rsh_i16() {
    int i;
    int j;
    i = -32768;  j = 1;
    check((i >> j), -16384);
    check((i >> j) < 0, 1);
    i = -32768;  j = 2;
    check((i >> j), -8192);
    check((i >> j) < 0, 1);
    i = -32768;  j = 3;
    check((i >> j), -4096);
    check((i >> j) < 0, 1);
    i = -32768;  j = 4;
    check((i >> j), -2048);
    check((i >> j) < 0, 1);
    i = -32768;  j = 5;
    check((i >> j), -1024);
    check((i >> j) < 0, 1);
    i = -32768;  j = 6;
    check((i >> j), -512);
    check((i >> j) < 0, 1);
    i = -113;  j = 1;
    check((i >> j), -57);
    check((i >> j) < 0, 1);
    i = -113;  j = 2;
    check((i >> j), -29);
    check((i >> j) < 0, 1);
    i = -113;  j = 3;
    check((i >> j), -15);
    check((i >> j) < 0, 1);
    i = -113;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -113;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -113;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 32767;  j = 1;
    check((i >> j), 16383);
    check((i >> j) < 0, 0);
    i = 32767;  j = 2;
    check((i >> j), 8191);
    check((i >> j) < 0, 0);
    i = 32767;  j = 3;
    check((i >> j), 4095);
    check((i >> j) < 0, 0);
    i = 32767;  j = 4;
    check((i >> j), 2047);
    check((i >> j) < 0, 0);
    i = 32767;  j = 5;
    check((i >> j), 1023);
    check((i >> j) < 0, 0);
    i = 32767;  j = 6;
    check((i >> j), 511);
    check((i >> j) < 0, 0);
}
void i16_rsh_i32() {
    int i;
    long j;
    i = -32768;  j = 1;
    check((i >> j), -16384);
    check((i >> j) < 0, 1);
    i = -32768;  j = 2;
    check((i >> j), -8192);
    check((i >> j) < 0, 1);
    i = -32768;  j = 3;
    check((i >> j), -4096);
    check((i >> j) < 0, 1);
    i = -32768;  j = 4;
    check((i >> j), -2048);
    check((i >> j) < 0, 1);
    i = -32768;  j = 5;
    check((i >> j), -1024);
    check((i >> j) < 0, 1);
    i = -32768;  j = 6;
    check((i >> j), -512);
    check((i >> j) < 0, 1);
    i = -113;  j = 1;
    check((i >> j), -57);
    check((i >> j) < 0, 1);
    i = -113;  j = 2;
    check((i >> j), -29);
    check((i >> j) < 0, 1);
    i = -113;  j = 3;
    check((i >> j), -15);
    check((i >> j) < 0, 1);
    i = -113;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -113;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -113;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 32767;  j = 1;
    check((i >> j), 16383);
    check((i >> j) < 0, 0);
    i = 32767;  j = 2;
    check((i >> j), 8191);
    check((i >> j) < 0, 0);
    i = 32767;  j = 3;
    check((i >> j), 4095);
    check((i >> j) < 0, 0);
    i = 32767;  j = 4;
    check((i >> j), 2047);
    check((i >> j) < 0, 0);
    i = 32767;  j = 5;
    check((i >> j), 1023);
    check((i >> j) < 0, 0);
    i = 32767;  j = 6;
    check((i >> j), 511);
    check((i >> j) < 0, 0);
}
int main() {
    i16_rsh_u8();
    i16_rsh_i8();
    i16_rsh_u16();
    i16_rsh_i16();
    i16_rsh_i32();
    printf("%s: %d tests finished, %d failures.\n",
    __FILE__, tests, failures);
}

