#include <stdio.h>

int tests = 0;
int failures = 0;
#define check(actual, expected) \
    tests++; if(((actual)) != ((expected))) { printf("test failed: line %d\n", __LINE__); failures++; }

void i8_rsh_u8() {
    signed char i;
    unsigned char j;
    i = -128;  j = 1;
    check((i >> j), -64);
    check((i >> j) < 0, 1);
    i = -128;  j = 2;
    check((i >> j), -32);
    check((i >> j) < 0, 1);
    i = -128;  j = 3;
    check((i >> j), -16);
    check((i >> j) < 0, 1);
    i = -128;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -128;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -128;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 1;
    check((i >> j), -11);
    check((i >> j) < 0, 1);
    i = -21;  j = 2;
    check((i >> j), -6);
    check((i >> j) < 0, 1);
    i = -21;  j = 3;
    check((i >> j), -3);
    check((i >> j) < 0, 1);
    i = -21;  j = 4;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -21;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
}
void i8_rsh_i8() {
    signed char i;
    signed char j;
    i = -128;  j = 1;
    check((i >> j), -64);
    check((i >> j) < 0, 1);
    i = -128;  j = 2;
    check((i >> j), -32);
    check((i >> j) < 0, 1);
    i = -128;  j = 3;
    check((i >> j), -16);
    check((i >> j) < 0, 1);
    i = -128;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -128;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -128;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 1;
    check((i >> j), -11);
    check((i >> j) < 0, 1);
    i = -21;  j = 2;
    check((i >> j), -6);
    check((i >> j) < 0, 1);
    i = -21;  j = 3;
    check((i >> j), -3);
    check((i >> j) < 0, 1);
    i = -21;  j = 4;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -21;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
}
void i8_rsh_u16() {
    signed char i;
    unsigned int j;
    i = -128;  j = 1;
    check((i >> j), -64);
    check((i >> j) < 0, 1);
    i = -128;  j = 2;
    check((i >> j), -32);
    check((i >> j) < 0, 1);
    i = -128;  j = 3;
    check((i >> j), -16);
    check((i >> j) < 0, 1);
    i = -128;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -128;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -128;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 1;
    check((i >> j), -11);
    check((i >> j) < 0, 1);
    i = -21;  j = 2;
    check((i >> j), -6);
    check((i >> j) < 0, 1);
    i = -21;  j = 3;
    check((i >> j), -3);
    check((i >> j) < 0, 1);
    i = -21;  j = 4;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -21;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
}
void i8_rsh_i16() {
    signed char i;
    int j;
    i = -128;  j = 1;
    check((i >> j), -64);
    check((i >> j) < 0, 1);
    i = -128;  j = 2;
    check((i >> j), -32);
    check((i >> j) < 0, 1);
    i = -128;  j = 3;
    check((i >> j), -16);
    check((i >> j) < 0, 1);
    i = -128;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -128;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -128;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 1;
    check((i >> j), -11);
    check((i >> j) < 0, 1);
    i = -21;  j = 2;
    check((i >> j), -6);
    check((i >> j) < 0, 1);
    i = -21;  j = 3;
    check((i >> j), -3);
    check((i >> j) < 0, 1);
    i = -21;  j = 4;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -21;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
}
void i8_rsh_i32() {
    signed char i;
    long j;
    i = -128;  j = 1;
    check((i >> j), -64);
    check((i >> j) < 0, 1);
    i = -128;  j = 2;
    check((i >> j), -32);
    check((i >> j) < 0, 1);
    i = -128;  j = 3;
    check((i >> j), -16);
    check((i >> j) < 0, 1);
    i = -128;  j = 4;
    check((i >> j), -8);
    check((i >> j) < 0, 1);
    i = -128;  j = 5;
    check((i >> j), -4);
    check((i >> j) < 0, 1);
    i = -128;  j = 6;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 1;
    check((i >> j), -11);
    check((i >> j) < 0, 1);
    i = -21;  j = 2;
    check((i >> j), -6);
    check((i >> j) < 0, 1);
    i = -21;  j = 3;
    check((i >> j), -3);
    check((i >> j) < 0, 1);
    i = -21;  j = 4;
    check((i >> j), -2);
    check((i >> j) < 0, 1);
    i = -21;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -21;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 1;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 2;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 3;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 4;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 5;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = -1;  j = 6;
    check((i >> j), -1);
    check((i >> j) < 0, 1);
    i = 1;  j = 1;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 2;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 3;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 4;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 5;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 1;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 36;  j = 1;
    check((i >> j), 18);
    check((i >> j) < 0, 0);
    i = 36;  j = 2;
    check((i >> j), 9);
    check((i >> j) < 0, 0);
    i = 36;  j = 3;
    check((i >> j), 4);
    check((i >> j) < 0, 0);
    i = 36;  j = 4;
    check((i >> j), 2);
    check((i >> j) < 0, 0);
    i = 36;  j = 5;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
    i = 36;  j = 6;
    check((i >> j), 0);
    check((i >> j) < 0, 0);
    i = 127;  j = 1;
    check((i >> j), 63);
    check((i >> j) < 0, 0);
    i = 127;  j = 2;
    check((i >> j), 31);
    check((i >> j) < 0, 0);
    i = 127;  j = 3;
    check((i >> j), 15);
    check((i >> j) < 0, 0);
    i = 127;  j = 4;
    check((i >> j), 7);
    check((i >> j) < 0, 0);
    i = 127;  j = 5;
    check((i >> j), 3);
    check((i >> j) < 0, 0);
    i = 127;  j = 6;
    check((i >> j), 1);
    check((i >> j) < 0, 0);
}
int main() {
    i8_rsh_u8();
    i8_rsh_i8();
    i8_rsh_u16();
    i8_rsh_i16();
    i8_rsh_i32();
    printf("%s: %d tests finished, %d failures.\n",
    __FILE__, tests, failures);
}

