echo off

c88 arith01
if errorlevel 1 goto stop
c88 arith02
if errorlevel 1 goto stop
c88 arith03
if errorlevel 1 goto stop
c88 arith04
if errorlevel 1 goto stop
c88 arith05
if errorlevel 1 goto stop
c88 arith06
if errorlevel 1 goto stop
c88 arith07
if errorlevel 1 goto stop
c88 arith08
if errorlevel 1 goto stop
c88 arith09
if errorlevel 1 goto stop
c88 arith10
if errorlevel 1 goto stop
c88 arith11
if errorlevel 1 goto stop
c88 arith12
if errorlevel 1 goto stop
c88 arith13
if errorlevel 1 goto stop
c88 arith14
if errorlevel 1 goto stop
c88 arith15
if errorlevel 1 goto stop
c88 arith16
if errorlevel 1 goto stop
c88 arith17
if errorlevel 1 goto stop
c88 arith18
if errorlevel 1 goto stop
c88 arith19
if errorlevel 1 goto stop
c88 arith20
if errorlevel 1 goto stop
c88 arith21
if errorlevel 1 goto stop
c88 arith22
if errorlevel 1 goto stop
c88 arith23
if errorlevel 1 goto stop
c88 arith24
if errorlevel 1 goto stop
c88 arith25
if errorlevel 1 goto stop
c88 arith26
if errorlevel 1 goto stop
c88 arith27
if errorlevel 1 goto stop
c88 arith28
if errorlevel 1 goto stop
c88 arith29
if errorlevel 1 goto stop
c88 arith30
if errorlevel 1 goto stop
c88 arith31
if errorlevel 1 goto stop
c88 arith32
if errorlevel 1 goto stop
c88 arith33
if errorlevel 1 goto stop
c88 arith34
if errorlevel 1 goto stop
c88 arith35
if errorlevel 1 goto stop
c88 arith36
if errorlevel 1 goto stop
c88 arith37
if errorlevel 1 goto stop
c88 arith38
if errorlevel 1 goto stop
c88 arith39
if errorlevel 1 goto stop
c88 arith40
if errorlevel 1 goto stop
c88 arith41
if errorlevel 1 goto stop
c88 arith42
if errorlevel 1 goto stop
c88 arith43
if errorlevel 1 goto stop
c88 arith44
if errorlevel 1 goto stop
c88 arith45
if errorlevel 1 goto stop
c88 arith46a
if errorlevel 1 goto stop
c88 arith46b
if errorlevel 1 goto stop
c88 arith47a
if errorlevel 1 goto stop
c88 arith47b
if errorlevel 1 goto stop
c88 arith48a
if errorlevel 1 goto stop
c88 arith48b
if errorlevel 1 goto stop
c88 arith49a
if errorlevel 1 goto stop
c88 arith49b
if errorlevel 1 goto stop
c88 arith50a
if errorlevel 1 goto stop
c88 arith50b
if errorlevel 1 goto stop
c88 arith51
if errorlevel 1 goto stop
c88 arith52
if errorlevel 1 goto stop
c88 arith53
if errorlevel 1 goto stop
c88 arith54
if errorlevel 1 goto stop
c88 arith55
if errorlevel 1 goto stop
c88 arith56
if errorlevel 1 goto stop
c88 arith57
if errorlevel 1 goto stop
c88 arith58
if errorlevel 1 goto stop
c88 arith59
if errorlevel 1 goto stop
c88 arith60
if errorlevel 1 goto stop
c88 arith61
if errorlevel 1 goto stop
c88 arith62
if errorlevel 1 goto stop
c88 arith63
if errorlevel 1 goto stop
c88 arith64
if errorlevel 1 goto stop
c88 arith65
if errorlevel 1 goto stop
c88 arith66
if errorlevel 1 goto stop
c88 arith67
if errorlevel 1 goto stop
c88 arith68
if errorlevel 1 goto stop
c88 arith69
if errorlevel 1 goto stop
c88 arith70
if errorlevel 1 goto stop
c88 arith71
if errorlevel 1 goto stop
c88 arith72
if errorlevel 1 goto stop
c88 arith73
if errorlevel 1 goto stop
c88 arith74
if errorlevel 1 goto stop
c88 arith75
if errorlevel 1 goto stop
c88 arith76
if errorlevel 1 goto stop
c88 arith77
if errorlevel 1 goto stop
c88 arith78
if errorlevel 1 goto stop
c88 arith79
if errorlevel 1 goto stop
c88 arith80a
if errorlevel 1 goto stop
c88 arith80b
if errorlevel 1 goto stop
c88 arith81a
if errorlevel 1 goto stop
c88 arith81b
if errorlevel 1 goto stop
c88 arith82a
if errorlevel 1 goto stop
c88 arith82b
if errorlevel 1 goto stop
c88 arith83
if errorlevel 1 goto stop
c88 arith84
if errorlevel 1 goto stop
c88 arith85
if errorlevel 1 goto stop
c88 arith86
if errorlevel 1 goto stop
c88 arith87
if errorlevel 1 goto stop

c88 arilit01
if errorlevel 1 goto stop
c88 arilit02
if errorlevel 1 goto stop
c88 arilit03
if errorlevel 1 goto stop
c88 arilit04
if errorlevel 1 goto stop
c88 arilit05
if errorlevel 1 goto stop
c88 arilit06
if errorlevel 1 goto stop
c88 arilit07
if errorlevel 1 goto stop
c88 arilit08
if errorlevel 1 goto stop
c88 arilit09
if errorlevel 1 goto stop
c88 arilit10
if errorlevel 1 goto stop
c88 arilit11
if errorlevel 1 goto stop

c88 compare
if errorlevel 1 goto stop

c88 compare1
if errorlevel 1 goto stop
c88 compare2
if errorlevel 1 goto stop
c88 compare3
if errorlevel 1 goto stop
c88 compare4
if errorlevel 1 goto stop
c88 compare5
if errorlevel 1 goto stop
c88 compare6
if errorlevel 1 goto stop
c88 compare7
if errorlevel 1 goto stop
c88 compare8
if errorlevel 1 goto stop
c88 compare9
if errorlevel 1 goto stop
c88 comparea
if errorlevel 1 goto stop
c88 compareb
if errorlevel 1 goto stop

bind arith01
if errorlevel 1 goto stop
bind arith02
if errorlevel 1 goto stop
bind arith03
if errorlevel 1 goto stop
bind arith04
if errorlevel 1 goto stop
bind arith05
if errorlevel 1 goto stop
bind arith06
if errorlevel 1 goto stop
bind arith07
if errorlevel 1 goto stop
bind arith08
if errorlevel 1 goto stop
bind arith09
if errorlevel 1 goto stop
bind arith10
if errorlevel 1 goto stop
bind arith11
if errorlevel 1 goto stop
bind arith12
if errorlevel 1 goto stop
bind arith13
if errorlevel 1 goto stop
bind arith14
if errorlevel 1 goto stop
bind arith15
if errorlevel 1 goto stop
bind arith16
if errorlevel 1 goto stop
bind arith17
if errorlevel 1 goto stop
bind arith18
if errorlevel 1 goto stop
bind arith19
if errorlevel 1 goto stop
bind arith20
if errorlevel 1 goto stop
bind arith21
if errorlevel 1 goto stop
bind arith22
if errorlevel 1 goto stop
bind arith23
if errorlevel 1 goto stop
bind arith24
if errorlevel 1 goto stop
bind arith25
if errorlevel 1 goto stop
bind arith26
if errorlevel 1 goto stop
bind arith27
if errorlevel 1 goto stop
bind arith28
if errorlevel 1 goto stop
bind arith29
if errorlevel 1 goto stop
bind arith30
if errorlevel 1 goto stop
bind arith31
if errorlevel 1 goto stop
bind arith32
if errorlevel 1 goto stop
bind arith33
if errorlevel 1 goto stop
bind arith34
if errorlevel 1 goto stop
bind arith35
if errorlevel 1 goto stop
bind arith36
if errorlevel 1 goto stop
bind arith37
if errorlevel 1 goto stop
bind arith38
if errorlevel 1 goto stop
bind arith39
if errorlevel 1 goto stop
bind arith40
if errorlevel 1 goto stop
bind arith41
if errorlevel 1 goto stop
bind arith42
if errorlevel 1 goto stop
bind arith43
if errorlevel 1 goto stop
bind arith44
if errorlevel 1 goto stop
bind arith45
if errorlevel 1 goto stop
bind arith46a
if errorlevel 1 goto stop
bind arith46b
if errorlevel 1 goto stop
bind arith47a
if errorlevel 1 goto stop
bind arith47b
if errorlevel 1 goto stop
bind arith48a
if errorlevel 1 goto stop
bind arith48b
if errorlevel 1 goto stop
bind arith49a
if errorlevel 1 goto stop
bind arith49b
if errorlevel 1 goto stop
bind arith50a
if errorlevel 1 goto stop
bind arith50b
if errorlevel 1 goto stop
bind arith51
if errorlevel 1 goto stop
bind arith52
if errorlevel 1 goto stop
bind arith53
if errorlevel 1 goto stop
bind arith54
if errorlevel 1 goto stop
bind arith55
if errorlevel 1 goto stop
bind arith56
if errorlevel 1 goto stop
bind arith57
if errorlevel 1 goto stop
bind arith58
if errorlevel 1 goto stop
bind arith59
if errorlevel 1 goto stop
bind arith60
if errorlevel 1 goto stop
bind arith61
if errorlevel 1 goto stop
bind arith62
if errorlevel 1 goto stop
bind arith63
if errorlevel 1 goto stop
bind arith64
if errorlevel 1 goto stop
bind arith65
if errorlevel 1 goto stop
bind arith66
if errorlevel 1 goto stop
bind arith67
if errorlevel 1 goto stop
bind arith68
if errorlevel 1 goto stop
bind arith69
if errorlevel 1 goto stop
bind arith70
if errorlevel 1 goto stop
bind arith71
if errorlevel 1 goto stop
bind arith72
if errorlevel 1 goto stop
bind arith73
if errorlevel 1 goto stop
bind arith74
if errorlevel 1 goto stop
bind arith75
if errorlevel 1 goto stop
bind arith76
if errorlevel 1 goto stop
bind arith77
if errorlevel 1 goto stop
bind arith78
if errorlevel 1 goto stop
bind arith79
if errorlevel 1 goto stop
bind arith80a
if errorlevel 1 goto stop
bind arith80b
if errorlevel 1 goto stop
bind arith81a
if errorlevel 1 goto stop
bind arith81b
if errorlevel 1 goto stop
bind arith82a
if errorlevel 1 goto stop
bind arith82b
if errorlevel 1 goto stop
bind arith83
if errorlevel 1 goto stop
bind arith84
if errorlevel 1 goto stop
bind arith85
if errorlevel 1 goto stop
bind arith86
if errorlevel 1 goto stop
bind arith87
if errorlevel 1 goto stop

bind arilit01
if errorlevel 1 goto stop
bind arilit02
if errorlevel 1 goto stop
bind arilit03
if errorlevel 1 goto stop
bind arilit04
if errorlevel 1 goto stop
bind arilit05
if errorlevel 1 goto stop
bind arilit06
if errorlevel 1 goto stop
bind arilit07
if errorlevel 1 goto stop
bind arilit08
if errorlevel 1 goto stop
bind arilit09
if errorlevel 1 goto stop
bind arilit10
if errorlevel 1 goto stop
bind arilit11
if errorlevel 1 goto stop

bind compare
if errorlevel 1 goto stop

bind compare1
if errorlevel 1 goto stop
bind compare2
if errorlevel 1 goto stop
bind compare3
if errorlevel 1 goto stop
bind compare4
if errorlevel 1 goto stop
bind compare5
if errorlevel 1 goto stop
bind compare6
if errorlevel 1 goto stop
bind compare7
if errorlevel 1 goto stop
bind compare8
if errorlevel 1 goto stop
bind compare9
if errorlevel 1 goto stop
bind comparea
if errorlevel 1 goto stop
bind compareb
if errorlevel 1 goto stop

runall

:stop
